### PR TITLE
Add voltage and power from mains

### PR DESCRIPTION
**Pull request by devdems**

### CODE REVIEW

**Comment by fluppie** [comment]
Nice! Would be cool if you can modify it for the EV meter voltages as well.
In quite some installs I use the Sensorbox together with an Eastron 1P or 3P EV meter. With the L1 (and sometimes also L2, L3) voltages I can estimate the power output and would even be able to do some kWh measuring (of course not the same accuracy as wired MID mains meter) with W to Wh/kWh calculation (emonCMS input processors support this).

**Comment by dingo35** [comment]
Why don't you rework your PR to a multiple register read scenario, where you have a function that calculates the distance between voltage and current registers, and if it doesn't exceed a threshold, read both of them in the same modbus request?

From the manufacturer:
1 byte costs approx. 1ms @ 9600bps, 1 register = 2 bytes so for 3 phases 6ms.
As long as all data stays below 40-50ms (incl. overhead) that should work.

**Comment by devdems** [comment]
I got P1 meter that reads those values directly from the grid so this is not something I need anymore.

**Comment by dingo35** [comment]
How about other people that need it?

**Comment by devdems** [comment]
They have a baseline there that can be improved.

**Pull request closed without merging**
