### PR TITLE
Idifference in Smart and Solar mode not converging to 0

### PR DESCRIPTION
**Pull request by demerstraat**
noticed Idifference never converges to 0. 
because integer division of 3 and 4 gives 0 as "increment" to Isetbalanced

### CODE REVIEW

**Comment by dingo35** [comment]
Thx for your PR, but this already came up 5 months ago.

If you can read Dutch, look af this post + the answers to it:
https://gathering.tweakers.net/forum/list_message/77542200#77542200

I'll check if the behaviour is still the same in current version...

**Comment by demerstraat** [comment]
oh okay, wasn't aware. 
I have read and understood your concerns regarding jumps and the circuit limits. 
possibly linked though to my other commit regarding "calibration" of PWM vs. actual current drawn by EV. 
the offset there also keeps Idifference from reaching true 0.
 
with the offset in place, I've not seen jumps over 0.1A over the circuit limit that weren't corrected within seconds

**Comment by dingo35** [comment]
Is that offset based on any IEEE or other standard documentation, or did it just seem like a good idea to pump the current up?

**Comment by demerstraat** [comment]
it is within the tolerance of 1 percentage point as per table A.5 of IEC 61851-1

**Comment by dingo35** [comment]
Great thx, I wouldnt want to bring the manufacturer into problems !!

**Comment by mstegen** [comment]
I have seen that there can be a difference in what the EVSE reports as the (max)charge current, and what the EV actually draws from the grid.
Took some measurements from my model S charging at 26A down to 6A 
Here are the results:
| advertised | measured | reported by EV|
| ----------- | ------------ | --------------|
| 26A | 24.2A | 24A |
| 25A | 23.8A | 24A |
| 24A | 23.1A | 24A |
| 23A | 22.0A | 23A |
| 22A | 21.0A | 22A |
| 16A | 15.0A | 16A |
| 6A | 5.1A | 6A |

So it almost always draws 1A too little current, even though the car reports the correct charge current
This should not be compensated for by increasing the PWM. It just the way it is, and other cars may behave different.
It's helpful when solar charging as you only need 5A to keep charging.

I agree that Idifference not converging to 0 could be improved with your PR.

**Comment by demerstraat** [comment]
thanks Michael, 
for information, 
I tested this again against Skoda Superb IV (1x16A OBC) and Ioniq 5 (3x16A OBC).

"correction" only worked on the entire range (6 to 16A) on Ioniq 5, 
most likely because the OBC will also take 1x32A in single phase configuration, 
so CP dutycycle of >16A are "accepted" and acted upon by the OBC.

for Superb IV "correction" only had effect between 6 and 15A, 
as the OBC does not seem to take into account CP dutycyles of >16A.

**Pull request closed without merging**
