### PR TITLE
OCPP support II

### PR DESCRIPTION
**Pull request by matth-x**
Fix OCPP-related RFID authorization behavior. Follow-up PR of https://github.com/dingo35/SmartEVSE-3.5/pull/82

### CODE REVIEW

**Comment by matth-x** [comment]
Looks like Hans has done a very good job in fixing the outstanding bugs. After a small modification of the debounce mechanism I was able to charge using my Plugsufing card without any observed failures. Later I will validate the UUID with the readout by the NXP PN532 reader.

What should be added to the TODO list of this PR?

**Comment by dingo35** [comment]
I think I noticed a bug (or it might be I don't understand Steve):
In Steve when a transaction is active, Datamanagement/Transactions, pressing the “Stop” button does not stop the charging session

**Comment by dingo35** [comment]
Also, I noticed when a SmartEVSE has no RFID reader installed, we are in "Access Denied", and I couldn't find any way to get out of it.
That might look like "intended behaviour", but some people use services like eFlux or ChargeHQ for their private use (e.g. billing to their employer), while the charger is physically not accessible for unauthorized users.

I would say, if an RFIDreader is installed, it should have this behaviour, but if RFIDreader = disabled it should be treated as a "free to use for all" charge point....

**Comment by dingo35** [comment]
Third point: when I stop a transaction, and I feed the SmarEVSE with EVMeter values; in the transaction I see "start value: 0" and "stop value: 0". Not sure if Im supposed to see EVmeter reading values here?
If not, where else?

NOTE: I just pushed a commit that reports the EVMeter type in the Credentials, instead of the MainsMeter type....

**Comment by matth-x** [comment]
The red "Stop" button is just to manually set transactions terminated in the backend. To actually start and stop transactions remotely, you need to go into Operations > OCPP 1.6 and execute the RemoteStartTransaction / RemoteStopTransaction operations.

If no RFID reader is installed, you still would want to have app-based charging, i.e. the customer authorizes the charge using the app provided by the CPO. Then the OCPP backend sends a RemoteStartTx / RemoteStopTx to the charger which eventually allows / stops charge. The alternative operational mode you're referring to is called "freevend mode", i.e. as soon as someone plugs in their EV, charging starts immediately, "for free". This is already supported by the OCPP lib and we could add an option for this in the dashboard.

The energy meter reading used for StartTx / StopTx is taken from here https://github.com/matth-x/SmartEVSE-3.5/blob/4d38feeba1c1b2b9432be510f4603d9a74fd8225/SmartEVSE-3/src/evse.cpp#L5635-L5637 Do you expect this return value to remain 0 throughout the charging process?

**Comment by dingo35** [comment]
On disabling OCPP via the web-interface of SmartEVSE, or changing the settings, Steve reports a transport error before closing the connection:
```
app_1  | [ERROR] 2024-07-12 11:08:39,758 de.rwth.idsg.steve.ocpp.ws.WebSocketLogger (qtp204322447-28) - [chargeBoxId=smartevse-01, sessionId=7e9f109a-bfb8-bcd2-64a5-c8d03b805eed] Transport error
app_1  | java.nio.channels.ClosedChannelException: null
app_1  | 	at org.eclipse.jetty.websocket.core.internal.WebSocketSessionState.onEof(WebSocketSessionState.java:169) ~[websocket-core-common-10.0.11.jar:10.0.11]
app_1  | 	at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession.onEof(WebSocketCoreSession.java:253) ~[websocket-core-common-10.0.11.jar:10.0.11]
app_1  | 	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.fillAndParse(WebSocketConnection.java:482) ~[websocket-core-common-10.0.11.jar:10.0.11]
app_1  | 	at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFillable(WebSocketConnection.java:340) ~[websocket-core-common-10.0.11.jar:10.0.11]
app_1  | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:319) ~[jetty-io-10.0.11.jar:10.0.11]
app_1  | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100) ~[jetty-io-10.0.11.jar:10.0.11]
app_1  | 	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53) ~[jetty-io-10.0.11.jar:10.0.11]
app_1  | 	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:412) ~[jetty-util-10.0.11.jar:10.0.11]
app_1  | 	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:381) ~[jetty-util-10.0.11.jar:10.0.11]
app_1  | 	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:268) ~[jetty-util-10.0.11.jar:10.0.11]
app_1  | 	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:138) ~[jetty-util-10.0.11.jar:10.0.11]
app_1  | 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:407) ~[jetty-util-10.0.11.jar:10.0.11]
app_1  | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894) ~[jetty-util-10.0.11.jar:10.0.11]
app_1  | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038) ~[jetty-util-10.0.11.jar:10.0.11]
app_1  | 	at java.lang.Thread.run(Thread.java:834) ~[?:?]
app_1  | [WARN ] 2024-07-12 11:08:39,759 de.rwth.idsg.steve.ocpp.ws.WebSocketLogger (qtp204322447-28) - [chargeBoxId=smartevse-01, sessionId=7e9f109a-bfb8-bcd2-64a5-c8d03b805eed] Connection is closed, status: CloseStatus[code=1006, reason=Session Closed]
``

**Comment by matth-x** [comment]
I don't have an explanation for these transport errors in SteVe, but nobody ever complained and probably they're not harmful.

**Review by dingo35 — APPROVED** [review]
Looks great!

**Comment by dingo35** [comment]
Ok I discovered the remote start/stop transactions, thanks for pointing that out! I pushed a commit on the energy meter readings, those are working now, great!

"If no RFID reader is installed, you still would want to have app-based charging, i.e. the customer authorizes the charge using the app provided by the CPO". I understand, but in our case the "app" could be provided by us, being the web-based interface? Not sure if that is the same as the "freevend" mode, because it would still be regulated by the user, except he wouldn't need to use the app provided by the CPO, but use the webapp on his home LAN.....

I still have problems testing, because of the RFID bugs you just solved, so I'm going to commit the changes you already made into my master repo. Don't like the old "waterfall" approach of the old days, rather be able to test your newest patches ...

**Comment by dingo35** [comment]
I could not find the hook to use for FirmwareUpdate, where should I find the hook/bridge/callback function?

**Comment by matth-x** [comment]
> in our case the "app" could be provided by us, being the web-based interface?

We don't need to take care of the app, it is provided by the e-mobility provider. The app will connect to the e-mobility provider which is connected to the OCPP backend which is connected with the SmartEVSE unit. The SmartEVSE will only receive the RemoteStart and RemoteStopTx via OCPP and that's it.

Freevend mode is an alternative operating mode. Then no authorization (via RFID or app) is required at all. We could add a setting to the dashboard for enabling freevend mode. Of course that assumes that the end user doesn't have access to the dashboard where they could allow themself to charge for free.

> Don't like the old "waterfall" approach of the old days, rather be able to test your newest patches ...

No problem to make smaller, atomic PRs from now on. The initial PR was bigger because it contained so much experimental code which I needed to revise many times as the functional scope grew bigger.

This PR should be good to go. Feel free to merge, then I will open new PRs for the other features.

> I could not find the hook to use for FirmwareUpdate, where should I find the hook/bridge/callback function?

MicroOCPP supports FW updates for the ESP32-Arduino platform out of the box. SmartEVSE doesn't customize that yet, so there are hook functions in this repository at the moment.

**Comment by dingo35** [comment]
We are miscommunicating.

The EVSEowner  pays the electricity bill, and he is the one controlling the webserver and the settings dashboard.
So he cannot charge "free".

He is the one deciding which EVowners have access to the EVSE; either physically, or by RFID authorization.

In most of our cases the EVSE owner would be the same person as the EVowner, and he would use OCPP to get his electrity costs reimbursed by his employer. He controls any access anyways, so again, no need for hidden dashboard.

So IMHO the dashboard does not need to be hidden or authorized. Keep in mind that the LCD screen is supposed to be physically unavailable to unauthorized users. They could easily change rfidreader settings...

**Comment by fluppie** [comment]
Maybe a simple user/pass auth could shield the interface from IT savvy guys :-). Interesting for business use where 2 or 4 of these are in the same network and IT didn't bother to put them in a seperate VLAN or so.
Ofcourse in a home + one man company situation, this is not needed. But maybe a simple optional login would be nice?

**Comment by matth-x** [comment]
When the OCPP backend doesn't come with an app, we don't need to provide a replacement in the web dashboard. Either the user authorizes via RFID card, or if the charger is in a private area, he disables authorization altogether by enabling the freevend mode.

Of course, in a semi-private / public area, the charger dashboard needs to be protected.

**Comment by dingo35** [comment]
"Of course, in a semi-private / public area, the charger dashboard needs to be protected."

I cannot think of a single situation where the LCD screen or the webserver would be publicly accessible, or even semi-accessible. It never is. If so people could change MaxMains and blow the fuses...

The only thing that could be public accessible is an RFID reader...

**Comment by dingo35** [comment]
Note that if the display says "Access Denied", you can press Menu, disable OCPP and RFID reader and charge.
So the display should be visible, but the buttons never be accessible for any non-expert user.

**Comment by matth-x** [comment]
Does this PR still contain any changes which are not on master yet?

**Comment by dingo35** [comment]
No files changed 0 so this one can be closed!

**Pull request closed without merging**
