### PR TITLE
OCPP fixes

### PR DESCRIPTION
**Pull request by matth-x**
This PR addresses issues which were discovered during the latest Plugfest (thanks again @dingo35 for testing!) and contains two changes which I would consider important for the final OCPP release. Unfortunately, I don't have access to my SmartEVSE right now, so I still need to validate these which I will do as soon as possible then.

Fixes:

- The WS Basic Auth key handler was broken in the latest version of MO-Mongoose. I fixed it in MO-Mongoose (https://github.com/matth-x/MicroOcppMongoose/pull/15) and pulled in the latest change here (a77d83c16ceeb1a3f66bb45202cc552ebd0176a2)
- The handling of 6- and 7-digit RFID UUIDs is inconsistent. In operational mode EnableAll /-One, the OCPP integration always assumed 6-digit UUIDs, but in RmtOcpp mode, it distinguished according to the first mode byte. 3eb921e454415d50f325ea32274891e0be49edca hopefully closes the gap by adding a further distinction
- When stopping a transaction, the display shows "Charging in progress" for a short moment which looks like a glitch (and is, actually). 406aa82dc0d5438dcc05931bfc3dd392a082a8a3 removes that message

Changes for Release:

- Upgrade to the latest MO version (899eb62ac79fe4919f0062517f90bceee28a4d06)
- Move all OCPP files into a dedicated folder. This increases the performance of the MO transaction store after it has been rewritten to crawling the base folder instead of building an index structure. This breaks existing deployments with OCPP, but I think now is the last chance for this before the official release

### CODE REVIEW

**Comment by dingo35** [comment]
Hi Matthias, great, thx for your work!

As to the SP2 authentication, during Plugfest there was some confusion (both by me and with my test partners, whom I sent screenshots so they could help me) on the field "Auth. Key"; at first I tried the password the other party provided, then I tried the b64 encoded string "Basic password".

Wouldnt it be clearer to rename that field to "Password (optional):" ?



Matthias Akstaller ***@***.***> schreef op 13 oktober 2024 12:35:06 EDT:

**Comment by dingo35** [comment]
When RFIDreader = Rmt/OCPP ,  screen says "Please Authorize", but tapping the tag does not do anything. The SmartEVSE log shows the tag id so it is read properly, but in Steve there is no "Unknown Tag" appearing so it should authorize, but it doesn't (also no "invalid" message on the screen).

This happens on both the 6 byte as on the 6 byte reader.

If I replace both github links in platformio.ini by the old ones, it all works fine, so the problem is either in MicroOCPP or in MicroOCPPMongoose.

**Comment by matth-x** [comment]
Hi @dingo35, sorry for the delayed response.

> Wouldnt it be clearer to rename that field to "Password (optional):" ?

Okay, let's change it. Password seems more intuitive here

> When RFIDreader = Rmt/OCPP , screen says "Please Authorize", but tapping the tag does not do anything.

Didn't find any plausible explanations so far. Unfortunately, I still don't my SmartEVSE at hand. Can you try the same thing (using the newer MO version) with the MO logs enabled? These flags should be set in platformio.ini:

```
    -D MO_DBG_LEVEL=MO_DL_DEBUG
    -D MO_TRAFFIC_OUT
```

You could send me the logs via e-mail as you want.

**Comment by dingo35** [comment]
Ok, this is the log (filtered only "your"  log messages:
[MO] debug (FirmwareService.cpp:285): Previous build number: 14:07:02 @Oct 24 2024, new build number: 14:07:02 @Oct 24 2024
[MO] Send: [2,"527e3346-ae7b-7848-8c87-f090f0919782","StatusNotification",{"connectorId":0,"errorCode":"NoError","status":"Available","timestamp":"2024-10-24T18:10:57Z"}]
[MO] Recv: [3,"527e3346-ae7b-7848-8c87-f090f0919782",{}]
[MO] Send: [2,"26cac7d2-f591-7010-1b76-ee420e23d5f4","StatusNotification",{"connectorId":1,"errorCode":"NoError","status":"Preparing","timestamp":"2024-10-24T18:10:57Z"}]
[MO] Recv: [3,"26cac7d2-f591-7010-1b76-ee420e23d5f4",{}]
[MO] debug (Connector.cpp:679): Begin transaction process (C148283E000000), prepare
[MO] ERROR (FilesystemUtils.cpp:96): Could not open file /ocpp/tx-1-0.jsn
[MO] ERROR (TransactionStore.cpp:146): FS error
[MO] ERROR (TransactionStore.cpp:106): FS error
[MO] ERROR (Connector.cpp:751): could not allocate Tx
[MO] debug (Connector.cpp:494): Status changed Preparing -> Faulted 
[MO] info (StatusNotification.cpp:52): New status: Faulted (connectorId 1)
[MO] Send: [2,"9b1e93e5-43c2-7d8b-e837-54cdbbfd0b2e","StatusNotification",{"connectorId":1,"errorCode":"PowerMeterFailure","info":"Communication with mains meter lost","status":"Faulted","timestamp":"2024-10-24T18:11:19Z"}]
[MO] Recv: [3,"9b1e93e5-43c2-7d8b-e837-54cdbbfd0b2e",{}]


So it seems to be a FS error.... which does not surprise me, although we agreed to move over from SPIFSS to LittleFS, AFAIK I have been running al those times without a LittleFS filesystem.... So it seems that up until now OCPP could do without local storage?

**Comment by matth-x** [comment]
Hi @dingo35, thanks for helping tracking it down. The transaction can't start because the tx file can't be stored on flash.

Moving all files to the dedicated OCPP folder doesn't work, because LittleFS expects that the folder is created before using it. I think that was different in earlier versions of the Arduino-LittleFS integration. Anyway, I haven't worked on that yet and would like to stick to the proven approach of storing all OCPP files in the root folder, even if that slows down some operations.

I tested the fix on a development board, but not the real SmartEVSE. Can you test it again?

**Comment by dingo35** [comment]
I had to increase the stack size of BlinkLed from 1024 to 2048, but apart from that all works fine now.

I cannot merge this PR when its draft, can you "undraft" it and resolve any conflicts that might have arisen because of the somewhat long response times?

Thanks!

**Comment by matth-x** [comment]
Perfect!

The auto-merge from upstream into this branch shows ~2k insertions and ~1k deletions ... I better open a rebased PR

**Pull request closed without merging**
